Multiple fixes
Michael-J-Scofield/discord-anti-spam pull request #122
Opened 2021-03-29 15:28 UTC by Scraayp

Fixed: 
- #121 
- #117

2021-04-02 14:49 UTC, Scraayp commented
Ready for review

2021-04-07 19:04 UTC, Michael-J-Scofield requested changes
looks good, I think we can merge once the formatting is consistent.

2021-04-07 19:04 UTC, Michael-J-Scofield commented on docs/index.html
> +	<link rel="icon"
can you make sure the indentation is consistent here? and in general clean up this file

2021-04-07 19:04 UTC, Michael-J-Scofield commented on index.js
> +      })
Indentation issue here too? Please autoformat so we're sure its consistent :)

2021-04-07 19:09 UTC, Michael-J-Scofield approved these changes

2021-04-07 19:10 UTC, merged